firstfile = input("enter your first file")
seccondfile = input("enter your seccond file")
f1 = open(firstfile, 'r')
f2 = open(seccondfile, 'r')
print('content of first file before appending \n ', f1.read())
print('content of seccond file before appending', f2.read())
f1.close()
f2.close()
f1 = open(firstfile, 'a+')
f2 = open(seccondfile, 'r')
f1.write(f2.read())
f1.seek(0)
f2.seek(0)
print('content of first file before appending \n ', f1.read())
print('content of seccond file before appending', f2.read()) 